title:              Z-log - Code Study
email:              eyz.1213@gmail.com
description:        My Note for Python Code Study 
author:             EYZ27
baseurl:            ""
url:                "https://eyz27.github.io/"

# Social Profiles
github_username:    EYZ27
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:    # out your google-analytics code

# Build settings
markdown:           
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
